default:
    suites:
        default:
            paths: [/var/www/angellistscraper/features/angellist.feature]
            contexts: [App\Tests\Behat\AngelContext]
    extensions:
        FriendsOfBehat\SymfonyExtension: ~
        DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
        Behat\MinkExtension:
            browser_name: chrome
            base_url: http://localhost
            sessions:
                default:
                    chrome:
                        api_url: 'http://localhost:9222'
#                        method: POST