default:
    suites:
        default:
            contexts:
                - App\Tests\Behat\CompanyContext
    extensions:
        FriendsOfBehat\SymfonyExtension: ~
        DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
        Behat\MinkExtension:
            browser_name: chrome
            base_url: http://localhost
            sessions:
                default:
                    chrome:
                        api_url: 'http://localhost:9222'